name: Package Application with Pyinstaller

on: 
  release:
    types: [published]
    tags:
        - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
    - 
      name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: main.exe
        path: ./
