name: Package Application with Pyinstaller

on: 
  release:
    types: [published]
    tags:
        - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Compile exe
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
    - 
      name: Upload artifact to workflow
      uses: actions/upload-artifact@v3
      with:
        name: pdf-overlay.exe
        path: ./
    -
      name: Get latest release info
      id: latest_release_info
      uses: jossef/action-latest-release-info@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Upload artifact to github release page
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
        asset_path: ./pdf-overlay.exe
        asset_name: pdf-overlay.exe
        asset_content_type: application/vnd.microsoft.portable-executable
