name: Package Application with Pyinstaller

on:
  push:
    branches:
        - main
  release:
    branches: 
        - main
    tags:
        - 'v*'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 4 * * 5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: main.exe
        path: ./
